-- Lead Magnet Simulator Phase 2A
-- Safe to run repeatedly.

create table if not exists public.lms_offers(
 id uuid primary key default gen_random_uuid(),name text not null,short_name text not null default '',description text not null default '',offer_type text not null default 'tour',location text not null default '',start_date date,end_date date,price numeric,currency text,target_segments text[] not null default '{}',status text not null default 'draft',user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.lms_motives(
 id uuid primary key default gen_random_uuid(),name text not null,description text not null default '',hypothesis text not null default '',target_segments text[] not null default '{}',status text not null default 'draft',user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.lms_messages(
 id uuid primary key default gen_random_uuid(),offer_id uuid not null references public.lms_offers(id) on delete cascade,motive_id uuid references public.lms_motives(id) on delete set null,name text not null,subject_line text not null default '',body text not null default '',version_number int not null default 1,parent_message_id uuid references public.lms_messages(id) on delete set null,user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,created_at timestamptz not null default now());
create table if not exists public.lms_simulations(
 id uuid primary key default gen_random_uuid(),message_id uuid not null references public.lms_messages(id) on delete cascade,offer_id uuid not null references public.lms_offers(id) on delete cascade,name text not null default '',status text not null default 'ready_for_simulation',audience_filter jsonb not null default '{}',audience_size int not null default 0,sample_size int not null default 0,model_name text,started_at timestamptz,completed_at timestamptz,user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,created_at timestamptz not null default now());
create table if not exists public.lms_simulation_responses(
 id uuid primary key default gen_random_uuid(),simulation_id uuid not null references public.lms_simulations(id) on delete cascade,person_id uuid not null references public.lms_people(id) on delete cascade,response_class text not null check(response_class in('ignore','read_only','tell_me_more','sign_me_up')),interest_score int not null check(interest_score between 0 and 100),credibility_score int not null check(credibility_score between 0 and 100),relevance_score int not null check(relevance_score between 0 and 100),novelty_score int not null check(novelty_score between 0 and 100),emotional_resonance_score int not null check(emotional_resonance_score between 0 and 100),primary_objection text not null default '',secondary_objection text,response_text text not null default '',reasoning_summary text not null default '',created_at timestamptz not null default now(),unique(simulation_id,person_id));
create table if not exists public.lms_simulation_insights(
 id uuid primary key default gen_random_uuid(),simulation_id uuid not null references public.lms_simulations(id) on delete cascade,insight_type text not null,title text not null,description text not null default '',supporting_count int not null default 0,created_at timestamptz not null default now());

alter table public.lms_offers enable row level security;alter table public.lms_motives enable row level security;alter table public.lms_messages enable row level security;alter table public.lms_simulations enable row level security;alter table public.lms_simulation_responses enable row level security;alter table public.lms_simulation_insights enable row level security;

do $$ declare t text; begin foreach t in array array['lms_offers','lms_motives','lms_messages','lms_simulations'] loop execute format('drop policy if exists %I on public.%I','lms own '+t,t);execute format('create policy %I on public.%I for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid())','lms own '+t,t);end loop;end $$;
drop policy if exists "lms own responses" on public.lms_simulation_responses;create policy "lms own responses" on public.lms_simulation_responses for all to authenticated using(exists(select 1 from public.lms_simulations s where s.id=simulation_id and s.user_id=auth.uid())) with check(exists(select 1 from public.lms_simulations s where s.id=simulation_id and s.user_id=auth.uid()));
drop policy if exists "lms own insights" on public.lms_simulation_insights;create policy "lms own insights" on public.lms_simulation_insights for all to authenticated using(exists(select 1 from public.lms_simulations s where s.id=simulation_id and s.user_id=auth.uid())) with check(exists(select 1 from public.lms_simulations s where s.id=simulation_id and s.user_id=auth.uid()));

create or replace function public.lms_audience_count(p_filters jsonb) returns integer language sql stable security definer set search_path=public as $$ select count(*)::int from lms_people where (nullif(p_filters->>'audience','') is null or audience_segment=p_filters->>'audience') and (nullif(p_filters->>'country','') is null or country=p_filters->>'country') and (nullif(p_filters->>'region','') is null or global_region=p_filters->>'region') and (nullif(p_filters->>'industry','') is null or industry=p_filters->>'industry') and (nullif(p_filters->>'purchasing_power','') is null or purchasing_power=p_filters->>'purchasing_power') and (nullif(p_filters->>'ageMin','') is null or age>=(p_filters->>'ageMin')::int) and (nullif(p_filters->>'ageMax','') is null or age<=(p_filters->>'ageMax')::int) $$;
revoke all on function public.lms_audience_count(jsonb) from public;grant execute on function public.lms_audience_count(jsonb) to authenticated;

create or replace function public.lms_simulation_summary(p_sim_id uuid) returns table(total_responses bigint,ignore_count bigint,read_only_count bigint,tell_me_more_count bigint,sign_me_up_count bigint,success_rate numeric,avg_interest numeric,avg_credibility numeric,avg_relevance numeric,avg_novelty numeric,avg_emotional_resonance numeric) language plpgsql stable security definer set search_path=public as $$ begin if not exists(select 1 from lms_simulations where id=p_sim_id and user_id=auth.uid()) then raise exception 'Access denied';end if;return query select count(*),count(*)filter(where response_class='ignore'),count(*)filter(where response_class='read_only'),count(*)filter(where response_class='tell_me_more'),count(*)filter(where response_class='sign_me_up'),round(100.0*count(*)filter(where response_class in('tell_me_more','sign_me_up'))/nullif(count(*),0),1),round(avg(interest_score),1),round(avg(credibility_score),1),round(avg(relevance_score),1),round(avg(novelty_score),1),round(avg(emotional_resonance_score),1) from lms_simulation_responses where simulation_id=p_sim_id;end $$;
revoke all on function public.lms_simulation_summary(uuid) from public;grant execute on function public.lms_simulation_summary(uuid) to authenticated;
