import { useEffect,useState } from 'react'; import { getMind,getMinds,getOptions } from './api'; import type {Filters,Mind} from './types';
const empty:Filters={search:'',audience:'',country:'',region:'',industry:'',power:'',ageMin:'',ageMax:''}; const label=(s:string)=>s==='cxo'?'CXO':s==='corporate_refugee'?'Corporate Refugee':'Consultant';
export default function Market(){const [f,setF]=useState(empty),[page,setPage]=useState(1),[rows,setRows]=useState<Mind[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<Mind|null>(null),[options,setOptions]=useState({countries:[] as string[],regions:[] as string[],industries:[] as string[]}),[error,setError]=useState('');
 useEffect(()=>{Promise.all([getOptions('country'),getOptions('global_region'),getOptions('industry')]).then(([countries,regions,industries])=>setOptions({countries,regions,industries})).catch(()=>{});},[]);
 useEffect(()=>{const t=setTimeout(()=>getMinds(page,f).then(r=>{setRows(r.rows);setTotal(r.total);setError('')}).catch(e=>setError(e.message)),250);return()=>clearTimeout(t)},[page,f]);
 const update=(k:keyof Filters,v:string)=>{setPage(1);setF(x=>({...x,[k]:v}))}; const pages=Math.max(1,Math.ceil(total/100));
 return <><div className="page-head"><div><h1>Synthetic Market</h1><p>{total.toLocaleString()} matching minds</p></div></div><div className="filters"><input className="search" placeholder="Search name, city, title, biography…" value={f.search} onChange={e=>update('search',e.target.value)}/><Select v={f.audience} on={v=>update('audience',v)} a={[["","All audiences"],["cxo","CXO"],["consultant","Consultant"],["corporate_refugee","Corporate Refugee"]]}/><Select v={f.country} on={v=>update('country',v)} a={[["","All countries"],...options.countries.map(x=>[x,x])]}/><Select v={f.region} on={v=>update('region',v)} a={[["","All regions"],...options.regions.map(x=>[x,x])]}/><Select v={f.industry} on={v=>update('industry',v)} a={[["","All industries"],...options.industries.map(x=>[x,x])]}/><Select v={f.power} on={v=>update('power',v)} a={[["","All purchasing power"],["mid","Mid"],["upper_mid","Upper-mid"],["high","High"],["very_high","Very high"]]}/><input type="number" min="25" max="55" placeholder="Age min" value={f.ageMin} onChange={e=>update('ageMin',e.target.value)}/><input type="number" min="25" max="55" placeholder="Age max" value={f.ageMax} onChange={e=>update('ageMax',e.target.value)}/></div>{error&&<div className="error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Name</th><th>Audience</th><th>Title</th><th>Country</th><th>Industry</th><th>Age</th><th>Curiosity</th><th>Challenge</th><th>Agency</th><th>Bullshit</th></tr></thead><tbody>{rows.map(m=><tr key={m.id} onClick={()=>getMind(m.id).then(setSelected)}><td><b>{m.first_name} {m.last_name}</b></td><td>{label(m.audience_segment)}</td><td>{m.job_title}</td><td>{m.country}</td><td>{m.industry}</td><td>{m.age}</td><td>{m.curiosity}</td><td>{m.challenge_deficit}</td><td>{m.agency_frustration}</td><td>{m.bullshit_tolerance}</td></tr>)}</tbody></table></div><div className="pager"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>← Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next →</button></div>{selected&&<Detail mind={selected} close={()=>setSelected(null)}/>}</>}
function Select({v,on,a}:{v:string;on:(v:string)=>void;a:string[][]}){return <select value={v} onChange={e=>on(e.target.value)}>{a.map(([x,l])=><option key={x} value={x}>{l}</option>)}</select>}
function Detail({mind:m,close}:{mind:Mind;close:()=>void}){const scores=['curiosity','skepticism','challenge_deficit','agency_frustration','bullshit_tolerance','professional_confidence','reinvention_readiness','decision_authority','budget_authority','international_exposure','willingness_to_travel','price_sensitivity'];return <div className="overlay" onClick={close}><article className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">{label(m.audience_segment)}</div><h2>{m.first_name} {m.last_name}</h2><p className="muted">{m.job_title} · {m.age} · {m.city?m.city+', ':''}{m.country}</p><p className="bio">{m.biography}</p><h3>Current tension</h3><p>{m.primary_tension}</p><p className="muted">Aspiration: {m.aspiration}</p><h3>Scores</h3>{scores.map(k=><div className="score" key={k}><span>{k.replaceAll('_',' ')}</span><div><i style={{width:`${Number(m[k])}%`}}/></div><b>{m[k]}</b></div>)}</article></div>}
