import'./messageLab.css';
import{useEffect,useMemo,useState}from'react';import{analyzeMessage,createRevision,deleteMessage,getSemanticProfile,listMessages,listMotives,listOffers,saveMessage,saveSemanticProfile}from'./phase2Api';import type{Message,Motive,Offer,SemanticProfile}from'./types';import SemanticPanel from'./SemanticPanel';

export default function MessageLab(){
  const[offers,setOffers]=useState<Offer[]>([]),[motives,setMotives]=useState<Motive[]>([]),[messages,setMessages]=useState<Message[]>([]),[selected,setSelected]=useState<Message|null>(null),[semantic,setSemantic]=useState<SemanticProfile|null>(null),[busy,setBusy]=useState(false),[form,setForm]=useState({offer_id:'',motive_id:'',name:'',subject_line:'',body:''}),[error,setError]=useState('');
  const load=()=>Promise.all([listOffers(),listMotives(),listMessages()]).then(([o,m,x])=>{setOffers(o);setMotives(m);setMessages(x);if(!form.offer_id&&o[0])setForm(f=>({...f,offer_id:o[0].id}))}).catch(e=>setError(e.message));
  useEffect(()=>{load()},[]);
  const words=useMemo(()=>form.body.trim()?form.body.trim().split(/\s+/).length:0,[form.body]);

  async function open(m:Message){setSelected(m);setForm({offer_id:m.offer_id,motive_id:m.motive_id??'',name:m.name,subject_line:m.subject_line,body:m.body});try{setSemantic(await getSemanticProfile(m.id))}catch(e){setError((e as Error).message)}}
  async function save(){try{const m=await saveMessage({...form,motive_id:form.motive_id||null});setSelected(m);setSemantic(null);await load()}catch(e){setError((e as Error).message)}}
  async function revise(){if(!selected)return;try{const r=await createRevision({...selected,offer_id:form.offer_id,motive_id:form.motive_id||null,name:form.name,subject_line:form.subject_line,body:form.body});await open(r);await load()}catch(e){setError((e as Error).message)}}
  async function analyze(){if(!selected){setError('Save the message before semantic analysis.');return}try{setBusy(true);setSemantic(await analyzeMessage(selected.id))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function saveSemantic(p:SemanticProfile){try{setSemantic(await saveSemanticProfile({...p,analysis_source:'manual'}))}catch(e){setError((e as Error).message)}}
  async function removeVersion(m:Message){if(!window.confirm(`Delete ${m.name} · V${m.version_number}?`))return;try{await deleteMessage(m.id);if(selected?.id===m.id){setSelected(null);setSemantic(null);setForm(f=>({...f,name:'',subject_line:'',body:''}))}await load()}catch(e){setError((e as Error).message)}}

  return <><div className="page-head"><div><h1>Message Lab</h1><p>One semantic reading per revision. Millions of Mind reactions can reuse it.</p></div></div>{error&&<div className="error">{error}</div>}<div className="two-col message-lab"><section className="card form compact-form"><label>Offer<select value={form.offer_id} onChange={e=>setForm({...form,offer_id:e.target.value})}>{offers.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Motive<select value={form.motive_id} onChange={e=>setForm({...form,motive_id:e.target.value})}><option value="">No motive</option>{motives.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Message name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Subject line<input value={form.subject_line} onChange={e=>setForm({...form,subject_line:e.target.value})}/></label><label>Body<textarea className="message-body" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><div className="muted">{form.body.length} characters · {words} words {selected?`· V${selected.version_number}`:''}</div><div className="actions"><button className="primary" onClick={save}>Save message</button>{selected&&<button onClick={revise}>Create revision</button>}</div></section><section className="card versions-card"><h3>Versions</h3>{messages.length===0?<p className="muted">No messages yet.</p>:messages.map(m=><div className={`version-row${selected?.id===m.id?' active':''}`} key={m.id}><button className="list-item version-open" onClick={()=>open(m)}><b>{m.name}</b><span>V{m.version_number} · {m.subject_line}</span></button><button className="version-delete" title="Delete version" aria-label={`Delete ${m.name} version ${m.version_number}`} onClick={()=>removeVersion(m)}>×</button></div>)}</section></div>{selected&&<SemanticPanel profile={semantic} onSave={saveSemantic} onAnalyze={analyze} busy={busy}/>}</>}
