export type Mind = {
  id: string;
  first_name: string;
  last_name: string;
  age: number;
  country: string;
  city: string | null;
  global_region: string;
  purchasing_power: string;
  audience_segment: string;
  job_title: string | null;
  industry: string | null;
  biography: string;
  primary_tension: string;
  secondary_tension: string | null;
  aspiration: string;
  curiosity: number;
  skepticism: number;
  challenge_deficit: number;
  agency_frustration: number;
  bullshit_tolerance: number;
  professional_confidence: number;
  reinvention_readiness: number;
  decision_authority: number;
  budget_authority: number;
  international_exposure: number;
  willingness_to_travel: number;
  price_sensitivity: number;
  [key: string]: string | number | null;
};
export type Filters = {
  search: string;
  audience: string;
  country: string;
  region: string;
  industry: string;
  power: string;
  ageMin: string;
  ageMax: string;
};
export type Offer = {
  id: string;
  name: string;
  short_name: string;
  description: string;
  offer_type: string;
  location: string;
  start_date: string | null;
  end_date: string | null;
  price: number | null;
  currency: string | null;
  urgency: string;
  cta: string;
  target_segments: string[];
  status: string;
  created_at: string;
  updated_at: string;
};
export type Motive = {
  id: string;
  name: string;
  description: string;
  hypothesis: string;
  current_belief: string;
  desired_belief: string;
  core_insight: string;
  evidence: string[];
  target_segments: string[];
  status: string;
  validation_status: string;
  audience_fit: number | null;
  current_belief_alignment: number | null;
  insight_novelty: number | null;
  perceived_truth: number | null;
  worldview_shift: number | null;
  identity_compatibility: number | null;
  evidence_strength: number | null;
  analysis_summary: string;
  recommendation: string;
  analysis_source: string | null;
  model_name: string | null;
  created_at: string;
  updated_at: string;
};
export type Message = {
  id: string;
  offer_id: string;
  motive_id: string | null;
  name: string;
  subject_line: string;
  body: string;
  ps: string;
  version_number: number;
  parent_message_id: string | null;
  created_at: string;
};
export type Simulation = {
  id: string;
  message_id: string;
  offer_id: string;
  name: string;
  status: string;
  audience_filter: Record<string, unknown>;
  audience_size: number;
  sample_size: number;
  model_name: string | null;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
};
export type PersonaFeedback = {
  id: string;
  behavior: string;
  belief_shift: number;
  trust_score: number;
  offer_fit: number;
  purchase_intent: number;
  current_belief: string;
  belief_after: string;
  primary_objection: string;
  recommendation: string;
  lms_people: {
    first_name: string;
    last_name: string;
    job_title: string | null;
    audience_segment: string;
  } | null;
};
export type SimulationSummary = {
  total_responses: number;
  ignore_count: number;
  read_only_count: number;
  tell_me_more_count: number;
  sign_me_up_count: number;
  success_rate: number;
  open_rate: number;
  read_rate: number;
  avg_activation: number;
  level_0: number;
  level_1: number;
  level_2: number;
  level_3: number;
  level_4: number;
  level_5: number;
  level_6: number;
  level_7: number;
  level_8: number;
  level_9: number;
  level_10: number;
  avg_interest: number;
  avg_credibility: number;
  avg_relevance: number;
  avg_novelty: number;
  avg_emotional_resonance: number;
  avg_belief_shift: number;
  avg_trust: number;
  avg_self_recognition: number;
  avg_offer_fit: number;
  avg_purchase_intent: number;
  avg_referral_intent: number;
  save_rate: number;
  forward_rate: number;
  book_rate: number;
  purchase_rate: number;
};
export type SemanticProfile = {
  id: string;
  message_id: string;
  curiosity_gap: number;
  specificity: number;
  credibility: number;
  novelty: number;
  intellectual_tension: number;
  personal_relevance: number;
  usefulness: number;
  urgency: number;
  emotional_resonance: number;
  sales_smell: number;
  risk_reduction: number;
  social_proof: number;
  identity_relevance: number;
  fear_pressure: number;
  opportunity_pull: number;
  proposition_clarity: number;
  cta_strength: number;
  narrative_pull: number;
  subject_open_pull: number;
  current_belief_alignment: number;
  insight_novelty: number;
  perceived_truth: number;
  worldview_shift: number;
  identity_compatibility: number;
  evidence_strength: number;
  offer_clarity: number;
  offer_fit: number;
  offer_desirability: number;
  offer_credibility: number;
  offer_urgency: number;
  offer_risk: number;
  offer_roi: number;
  copy_subject: number;
  hook_strength: number;
  readability: number;
  authenticity: number;
  story_flow: number;
  diagnosis: string;
  summary: string;
  key_themes: string[];
  analysis_source: string;
  model_name: string | null;
  created_at: string;
  updated_at: string;
};
